### ISSUE TITLE
Possibly curses-related issue

### ISSUE THREAD

**Issue by injcristianrojas** [Orange-Cyberdefense/arsenal#69] opened 2023-12-03 20:48 UTC
Having worked around the IOCTL issue, I now found a new one. I have a dual environment in which I run Arsenal (my main machine is Fedora 39, and my pentest machine is a virtualized Kali Linux 2023.4). When I run arsenal on my fedora machine it works correctly, but on my Kali machine it gives me this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.virtualenvs/arsenal/lib/python3.11/site-packages/arsenal/modules/gui.py", line 319, in run
    wrapper(args_menu.run)
  File "/usr/lib/python3.11/curses/__init__.py", line 101, in wrapper
    endwin()
_curses.error: endwin() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.virtualenvs/arsenal/bin/arsenal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/.virtualenvs/arsenal/lib/python3.11/site-packages/arsenal/app.py", line 185, in main
    App().run()
  File "/home/kali/.virtualenvs/arsenal/lib/python3.11/site-packages/arsenal/app.py", line 64, in run
    self.start(args, cheatsheets)
  File "/home/kali/.virtualenvs/arsenal/lib/python3.11/site-packages/arsenal/app.py", line 71, in start
    cmd = gui.run(cheatsheets)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.virtualenvs/arsenal/lib/python3.11/site-packages/arsenal/modules/gui.py", line 827, in run
    wrapper(self.cheats_menu.run)
  File "/usr/lib/python3.11/curses/__init__.py", line 101, in wrapper
    endwin()
_curses.error: endwin() returned ERR
```

It looks like it's a ncurses-related issue. On Fedora 39, the installed version of ncurses is 6.4.20230520. On Kali, the installed version is 6.4.20231121.

**Comment by joblinours** [comment] 2023-12-07 14:09
I have the same problem, I've been trying to fix it for 2 days and haven't found it yet.

**Comment by purpl3horse** [comment] 2023-12-11 14:55
Same issue here on latest Kali Linux 2023.4 vm

**Comment by joblinours** [comment] 2023-12-11 16:28
I have just run my linux kali on python 3.12, unfortunately no change on the result.

**Comment by v1k1ngfr** [comment] 2023-12-12 10:33
Hi !
Thanks for reporting the issue, we will have a look at this error.

**Comment by trb143** [comment] 2023-12-27 08:10
Not an expert on curses but found this thread which may help find the fix.
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1944374.html

**Comment by v1k1ngfr** [comment] 2023-12-28 13:51
Hey !

Because of TIOCSTI patch applied recently on Linux Kernel, we need to re-implement some Arsenal functions (which can take some time).
Thanks @slasheur7 helping at troubleshooting this.

Here is a workaround, execute as root :
`sysctl -w dev.tty.legacy_tiocsti=1`

If you want this workaround to survive a reboot, add the following configuration to sysctl.conf file (root permission needed) : 
`echo "dev.tty.legacy_tiocsti=1" >> /etc/sysctl.conf`

It works on the current Kali 2023.4 (python 3.11.7 and 3.12.1) and should also work on other Linux distro. 

Of course there is security concern (ie : if you are not already root on your Linux). More information about TIOCTSI in the following kernel commit log : 
[https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=83efeeeb3d04b22aaed1df99bc70a48fe9d22c4d](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=83efeeeb3d04b22aaed1df99bc70a48fe9d22c4d)

**Comment by joblinours** [comment] 2023-12-29 22:40
Hello,

After testing your solution under kali 2023.4 and in python 3.11.7 the error has still not changed.

I will continue to try tomorrow but currently still the same error message 😁

**Comment by injcristianrojas** [comment] 2023-12-29 22:43
@joblinours what solution? Any specific commit?

**Comment by joblinours** [comment] 2023-12-30 09:18
@injcristianrojas 
the temporary solution proposed by @v1k1ngfr by adding the "dev.tty.legacy_tiocsti=1" attribute to /etc/sysctl.conf

**Comment by injcristianrojas** [comment] 2023-12-30 16:05
@joblinours the IOCTL issue is mentioned in the README. This ticket is for another issue.

**Comment by v1k1ngfr** [comment] 2024-01-08 14:00
@injcristianrojas we are not able to reproduce your issue related to ncurses, could you give steps you followed ?

**Comment by trb143** [comment] 2024-01-08 14:21
@v1k1ngfr are you referring to the original issue or the  "dev.tty.legacy_tiocsti=1" one?
If it is the original one I can confirm the issues.  Arsenal works fine on my Fedora box but fails on my old Kali box and the new rebuild of my Kali box with no customizations.  If you see the comment above this has also been found by the HG project but their fix did not seem to work for Arsenal.

**Comment by kib3rvo1n** [comment] 2024-01-08 14:28
When you install the latest version of kali you will have the error as above. i tried to install with pip an manual but both does not fix it. dev.tty.legacy_tiocsti=1 is a fix for the kernel update problem and does not fix this error. The problem is in cursed module. I have to rebuild kali because its foobar now because of my current attempts to fix it, will try to find a fix when i'm up again.

**Comment by injcristianrojas** [comment] 2024-01-08 16:08
@v1k1ngfr sure. I'm running arsenal on Kali without a virtualenv or pip packages installed, on Kali 2023.4. Just installed it using pip install with deb-based dependencies installed. The error appears every time I exit arsenal, either due to Ctrl-C or when getting a command.

If you have any more questions, please let me know.

**Comment by purpl3horse** [comment] 2024-01-14 14:13
> @injcristianrojas we are not able to reproduce your issue related to ncurses, could you give steps you followed ?

Have you tried on the latest version of Kali Linux (2023.4?) I have tried on several machines that were recently upgraded. All give the same error reported by OP

**Comment by forlorn1** [comment] 2024-01-25 01:03
On latest Kali,  I added 

def exception_handler(exception_type, exception, traceback):
    print ("%s: %s" % (exception_type.__name__, exception) )
sys.excepthook = exception_handler
 
above the "if __name__" in the arsenal main program.  Now when I exit arsenal on kali I just get

error: endwin() returned ERR

Instead of 30 lines of traceback.  Could probably remove the print and ignore  it completely, but if  something else goes wrong, I would like to know it.

**Comment by Bungie25** [comment] 2024-02-01 18:03
Same issue
└─   a                                                                                                                                                                                                                                                          [ 5:52pm 1 ⨯ ]
Traceback (most recent call last):
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/modules/gui.py", line 382, in run
    curses.endwin()
_curses.error: endwin() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r3dkn33/.local/bin/arsenal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/app.py", line 185, in main
    App().run()
  File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/app.py", line 64, in run
    self.start(args, cheatsheets)
  File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/app.py", line 71, in start
    cmd = gui.run(cheatsheets)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/modules/gui.py", line 827, in run
    wrapper(self.cheats_menu.run)
  File "/usr/lib/python3.11/curses/__init__.py", line 101, in wrapper
    endwin()
_curses.error: endwin() returned ERR





Followed these steps to install on most recent version of Kali

```
python3 -m pip install arsenal-cli
add this alias a='arsenal' to .zshrc
```

**Comment by Bungie25** [comment] 2024-02-02 13:10
Just to confirm are these the locations?
```
/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/modules/gui.py
/usr/lib/python3.11/curses/__init__.py
```

**Comment by purpl3horse** [comment] 2024-02-02 13:28
> Just to confirm are these the locations?
> 
> ```
> /home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/modules/gui.py
> /usr/lib/python3.11/curses/__init__.py
> ```
> 
> If they are the correct locations. the output after running arsenal is
> 
> ```
> Traceback (most recent call last):
> File "/home/r3dkn33/.local/bin/arsenal", line 8, in <module>                                                                                                  
> 
> sys.exit(main())
>          ^^^^^^
> 
> File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/app.py", line 185, in mainApp().run()
> File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/app.py", line 64, in run self.start(args, cheatsheets)
> File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/app.py", line 161, in start self.prefil_shell_cmd(cmd)
> File "/home/r3dkn33/.local/lib/python3.11/site-packages/arsenal/app.py", line 178, in prefil_shell_cmd
> fcntl.ioctl(stdin, termios.TIOCSTI, c)
> OSError: [Errno 5] Input/output error
> ```

You have the correct locations, to solve that last error run this:
`sudo sysctl -w dev.tty.legacy_tiocsti=1`

**Comment by purpl3horse** [comment] 2024-02-02 13:29
> For testing purposes: if you comment out the three occurrences of `endwin()` in `gui.py`, along with the `endwin()` call in the wrapper function of curses' `__init__.py`, Arsenal begins to work again correctly with no errors.

Confirmed. I edited those 2 files in the following locations:

```
/home/user/.local/lib/python3.11/site-packages/arsenal/modules/gui.py
/usr/lib/python3.11/curses/__init__.py
```

**Comment by Bungie25** [comment] 2024-02-02 13:41
> sudo sysctl -w dev.tty.legacy_tiocsti=1

Perfect thank you - confirmed as working

**Comment by r3dp0int** [comment] 2024-02-04 05:41
As you've probably noticed, that small fix isn't perfect as your terminal is then messed up after returning from Arsenal.
But it does provide some insight into the permanent fix, which I believe is just a matter of ensuring a refresh() call is made in between calls of endwin()

**Comment by r3dp0int** [comment] 2024-02-04 09:17
I think I've come up with the correct solution, I'll issue a pull request soon.

**Comment by v1k1ngfr** [comment] 2024-02-08 17:43
Fixed by @r3dp0int

**Closed** 2024-02-08 17:42 UTC
Labels: bug
