### ISSUE TITLE
Error when selecting command

### ISSUE THREAD

**Issue by PaulAZC** [Orange-Cyberdefense/arsenal#74] opened 2024-01-12 09:29 UTC
Hello,

I have installed the tool correctly and it works normally when the commands are displayed. However, when it comes to selecting the command with the enter key once the various arguments have been entered for it, here's the error returned that I can't correct: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XX/.local/lib/python3.11/site-packages/arsenal/modules/gui.py", line 382, in run
    curses.endwin()
_curses.error: endwin() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XX/.local/bin/arsenal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/XX/.local/lib/python3.11/site-packages/arsenal/app.py", line 185, in main
    App().run()
  File "/home/XX/.local/lib/python3.11/site-packages/arsenal/app.py", line 64, in run
    self.start(args, cheatsheets)
  File "/home/XX/.local/lib/python3.11/site-packages/arsenal/app.py", line 71, in start
    cmd = gui.run(cheatsheets)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/XX/.local/lib/python3.11/site-packages/arsenal/modules/gui.py", line 827, in run
    wrapper(self.cheats_menu.run)
  File "/usr/lib/python3.11/curses/__init__.py", line 101, in wrapper
    endwin()
_curses.error: endwin() returned ERR
```

My python version is 3.11.7.
Do you know how to correct it ? 

Thank you for your work.

**Comment by trb143** [comment] 2024-01-12 16:09
Duplicate of https://github.com/Orange-Cyberdefense/arsenal/issues/69

**Comment by v1k1ngfr** [comment] 2024-01-15 09:30
Duplicate of https://github.com/Orange-Cyberdefense/arsenal/issues/69

**Closed by v1k1ngfr** 2024-01-15 09:30 UTC
