### ISSUE TITLE
Error whenever i try to run command

### ISSUE THREAD

**Issue by Andreddi** [Orange-Cyberdefense/arsenal#72] opened 2023-12-13 09:12 UTC
I installed with the pip3 command, on the latest Kali version. After starting arsenal and selecting a random command, and then filling out the parameters and pressing enter, I get the following error. 

I've already tried on another Kali machine, with an older version to verify, and I see the same thing. 

It's the same for all tools. 

These are the current versions of the required packages.

```
>python3 -m pip install arsenal-cli


Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/mitm6-0.3.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330                                                                                                                                    
Requirement already satisfied: arsenal-cli in /home/kali/.local/lib/python3.11/site-packages (1.1.1)                                                                                                           
Requirement already satisfied: libtmux in /home/kali/.local/lib/python3.11/site-packages (from arsenal-cli) (0.25.0)
Requirement already satisfied: docutils in /home/kali/.local/lib/python3.11/site-packages (from arsenal-cli) (0.20.1)
Requirement already satisfied: pyperclip in /usr/lib/python3/dist-packages (from arsenal-cli) (1.8.2)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from arsenal-cli) (6.0.1)
Requirement already satisfied: pyfzf in /home/kali/.local/lib/python3.11/site-packages (from arsenal-cli) (0.3.1)
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/arsenal/modules/gui.py", line 319, in run
    wrapper(args_menu.run)
  File "/usr/lib/python3.11/curses/__init__.py", line 101, in wrapper
    endwin()
_curses.error: endwin() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/bin/arsenal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/arsenal/app.py", line 185, in main
    App().run()
  File "/home/kali/.local/lib/python3.11/site-packages/arsenal/app.py", line 64, in run
    self.start(args, cheatsheets)
  File "/home/kali/.local/lib/python3.11/site-packages/arsenal/app.py", line 71, in start
    cmd = gui.run(cheatsheets)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/arsenal/modules/gui.py", line 827, in run
    wrapper(self.cheats_menu.run)
  File "/usr/lib/python3.11/curses/__init__.py", line 101, in wrapper
    endwin()
_curses.error: endwin() returned ERR
```

**Comment by trb143** [comment] 2023-12-13 14:19
Duplicate of https://github.com/Orange-Cyberdefense/arsenal/issues/69

**Comment by Andreddi** [comment] 2023-12-14 07:32
Closing, as it's a duplicate.

**Closed** 2023-12-14 07:32 UTC
